import os
import sys
from pathlib import Path

# Add libs/agno to sys.path
repo_root = Path(__file__).parent.parent.resolve()
sys.path.append(str(repo_root / "libs" / "agno"))

from agno.registry.loader import RegistryLoader
from agno.utils.log import set_log_level_to_debug

def test_loader():
    set_log_level_to_debug()
    registry_path = repo_root / "registry"
    loader = RegistryLoader(registry_path)
    
    print(f"Scanning registry at: {registry_path}")
    registry = loader.load_all()
    
    print("\n--- Registry Summary ---")
    print(f"Tools loaded: {len(registry.tools)}")
    for tool in registry.tools:
        print(f"  - {tool}")
        
    print(f"Agents loaded: {len(registry.agents)}")
    for agent in registry.agents:
        print(f"  - Agent: {agent.name}")
        
    print(f"Workflows loaded: {len(registry.workflows)}")
    for workflow in registry.workflows:
        print(f"  - Workflow: {workflow.name}")
        
    print(f"Guardrails loaded: {len(registry.guardrails)}")
    for guardrail in registry.guardrails:
        print(f"  - Guardrail: {guardrail.name}")

    # Verify lookups
    print("\n--- Lookup Tests ---")
    researcher = registry.get_agent("researcher") # ID might be None, but name is Researcher
    # Wait, get_agent uses ID. Let's see if our researcher has an ID.
    # Our example didn't set an ID, so it might be None or autogenerated.
    
    # Let's check names instead for this test
    for agent in registry.agents:
        if agent.name == "Researcher":
            print("Successfully found Researcher agent by name.")
            
    for guardrail in registry.guardrails:
        if guardrail.name == "PII Filter":
            print("Successfully found PII Filter guardrail by name.")

if __name__ == "__main__":
    test_loader()
